### ISSUE TITLE
securing api calls from the db using your middleware

### ISSUE THREAD

**Issue by aalbrecht17235** [amazingandyyy/mern-stack#12]
We're having trouble creating new secure api calls, and were hoping you could help us out. Thanks!

**Comment by amazingandyyy** [comment]
middleware in `epxress` are something like `fn(req, res, next){}`

**Comment by amazingandyyy** [comment]
and you can see I am passing the header in client sied: https://github.com/amazingandyyy/mern-stack/blob/master/client/src/actions/index.js#L15

**Comment by aalbrecht17235** [comment]
thanks!
