### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tweetzal** [amazingandyyy/mern-stack#6]
Great repo!

If I replace the mongodb url on lie 14 in server js with a mongolab url, will this repo work or do I need to do more to see it in action. Thanks again ! Mo

**Comment by amazingandyyy** [comment]
Yes it should be okay, but remember to use environment variable of your mongo url, since it should contain sensitive informations, btw also  remember to create JWT_SECRET in env as well. 

But since .env file is ignored by git, you mind be careful about this issue.

**Comment by tweetzal** [comment]
Thanks again !

**Comment by tweetzal** [comment]
Application runs but signup doesnt work - throws server error. If you have some example it will be handy ;)

**Comment by amazingandyyy** [comment]
I hope my reply to #7 works. Let me know any further questions, I appreciate any questions!
