### ISSUE TITLE
Oops! Server Error, try later.

### ISSUE THREAD

**Issue by tweetzal** [amazingandyyy/mern-stack#7]
Great project, I clone repo and followed client instructions.
$ cd client
$ npm i
$ npm run dev

Project runs but always throws 
`Oops! Server Error, try later.`

When I try signup up ?

Any ideas why ... see screenshot ....[
![screen shot 2018-02-26 at 10 31 05](https://user-images.githubusercontent.com/2478550/36665779-685119f2-1ae0-11e8-8abe-219bd40501e0.png)
](url)

**Comment by amazingandyyy** [comment]
in another terminal session(usually command N or T), 
then `cd ../rout/to/the/server` then do `npm run dev`

**Comment by amazingandyyy** [comment]
remember you need mongoDB installed, 

https://gist.github.com/nrollr/9f523ae17ecdbb50311980503409aeb3

**Comment by amazingandyyy** [comment]
does it work? @tweetzal
